apiVersion: v1
kind: Namespace
metadata:
  name: housekeeper-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: housekeeper-operator-manager
  namespace: housekeeper-system
  labels:
    control-plane: housekeeper-operator-manager
spec:
  selector:
    matchLabels:
      control-plane: housekeeper-operator-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: housekeeper-operator-manager
    spec:
      containers:
      - command:
        - /housekeeper-operator-manager
        image: hub.oepkgs.net/nestos/nkd/{arch}/housekeeper-operator-manager:0.1.0
        imagePullPolicy: Always
        name: housekeeper-operator-manager
        securityContext:
          allowPrivilegeEscalation: false
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
      terminationGracePeriodSeconds: 10
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
      tolerations:
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: housekeeper-controller-manager
  namespace: housekeeper-system
  labels:
    control-plane: housekeeper-controller-manager
spec:
  selector:
    matchLabels:
      control-plane: housekeeper-controller-manager
  template:
    metadata:
      labels:
        control-plane: housekeeper-controller-manager
    spec:
      tolerations:
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "node-role.kubernetes.io/worker"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
       - name: housekeeper-controller-manager
         command:
          - /housekeeper-controller-manager
         image: hub.oepkgs.net/nestos/nkd/{arch}/housekeeper-controller-manager:0.1.0
         imagePullPolicy: Always
         volumeMounts:
          - name: upgrade-daemon
            mountPath: /var/nkd
         env:
          - name: NODE_NAME
            valueFrom:
             fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
      volumes:
        - name: upgrade-daemon
          hostPath:
            path: /var/nkd