apiVersion: v1
kind: Namespace
metadata:
  name: housekeeper-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: housekeeper-operator-manager
  namespace: housekeeper-system
  labels:
    control-plane: housekeeper-operator-manager
spec:
  selector:
    matchLabels:
      control-plane: housekeeper-operator-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: housekeeper-operator-manager
    spec:
      containers:
      - command:
        - /housekeeper-operator-manager
        image: housekeeper-operator:latest
        name: housekeeper-operator-manager
        securityContext:
          allowPrivilegeEscalation: false
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
      terminationGracePeriodSeconds: 10
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
      tolerations:
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
